Print _objectAlignmentInBytes
error: ‘_objectAlignmentInBytes’ was not declared in
this scope.

I think the error occured due to improper syntax.

Signed-off-by: Amarpreet Singh amarpreet1997@gmail.com